### ISSUE TITLE
Integrate webdriver in parallel execution

### ISSUE THREAD

**Issue by rajann44** [Vandna-Pandey/ParallelTestExample#1]
Hello @Vandna-Pandey I see that test are running in parallel but there are no actual tests.
I need your help if possible, because when I am trying to run test cases with webdriver its not working as expectedly.

e.g.
I have 5 test cases
thread-count 2

The test run with 2 chrome instances: but instance1 only run 1 test AND instance2 run other 4.
Here the dummy project: https://github.com/rajann44/SelMvn

Or you can either make changes in your repo and will check then. Thanks!

**Comment by Vandna-Pandey** [comment]
> Hello @Vandna-Pandey I see that test are running in parallel but there are no actual tests. I need your help if possible, because when I am trying to run test cases with webdriver its not working as expectedly.
> 
> e.g. I have 5 test cases thread-count 2
> 
> The test run with 2 chrome instances: but instance1 only run 1 test AND instance2 run other 4. Here the dummy project: https://github.com/rajann44/SelMvn
> 
> Or you can either make changes in your repo and will check then. Thanks!

@rajann44 
Updated the code from my end just check and let me know for any query.
Note: You can pass the your browser instances wherever required.

**Comment by rajann44** [comment]
Thanks @Vandna-Pandey for quick response. Really appreciate it.
But I am seeing issue with latest commit:
1. Only 1 test runs per browser instance
2. Initially i see 2 browser instance getting launched, after the execution of 2 is completed. I see 3rd instance of browser opening.

Expected Behaviour of true parallelisation:
There should only be 2 browser instances AND 5 tests should run in distributed manner
e.g.
1. browser 1 browser 2 launches: running test3 & test5
2. test5 is completed, test4 start running on browser2
3. test3 is completed, test2 start running on browser1
4. test4 is completed, test1 start running on browser2
5. Both browser instances are closed.

**Comment by rajann44** [comment]
O/P of latest commit
![Screenshot 2022-08-24 at 5 57 07 PM](https://user-images.githubusercontent.com/60035342/186418919-ee59cfd8-9770-4381-ae7d-c288f6106ec4.png)

**Comment by Vandna-Pandey** [comment]
> O/P of latest commit ![Screenshot 2022-08-24 at 5 57 07 PM](https://user-images.githubusercontent.com/60035342/186418919-ee59cfd8-9770-4381-ae7d-c288f6106ec4.png)

Go for the console log - It will print some Thread Id  
Search for these statement 

The thread ID for fourth method - 24
The thread ID for fifth method - 23
The thread ID for third method - 23
The thread ID for first method - 24
The thread ID for second method - 23

Note: It is not running one after another(Sequentially) You won't we able to see 2 different instances of browsers getting launched for same testcases, Total 5 Test methods we have in one class. When I assigned thread-count="2", It means it will run parallelly on 2 threads or 2 instances (Here I have tried to print thread ids), 1st, and 4th run with the help of thread id 24 and remaining 2nd, 3rd and 5th run with the help of thread id 23. 

This is happing parallelly now if you will change thread-count="5", it will run in 5 separate threads means for each one testcase it will create the new thread. I hope now it is clear. Please attached screenshot for the reference
 
![image](https://user-images.githubusercontent.com/63224926/186424564-5283f507-5c80-4573-84fe-3bbb4ec3e251.png)
![image](https://user-images.githubusercontent.com/63224926/186424695-171c2e73-3f68-4844-9a14-02cfebf5afe2.png)

**Comment by rajann44** [comment]
@Vandna-Pandey Here is the execution of your tests at my end.

https://user-images.githubusercontent.com/60035342/186484474-cf5c1e98-8f1e-4d3c-af3f-213131c633ed.mov

My expectation:
1. keep the number of active browser based on thread-count in xml
2. run 2 tests in parallel mode on 2 active instance of browser
3. if any test is complete, the browser should either be closed and new browser instance should be launched
OR
if any test is complete, next test run on that browser.

**Comment by rajann44** [comment]
@Vandna-Pandey This is execution of my test framework where I am trying to run test parallely.
But at my end below if happening
1. 2 browser instance gets launched based on thread-count in xml
2. 2 test run on 2 browser instance, but later the remaining 3 tests are getting executed on 1 browser only. Rather being getting distributed.


https://user-images.githubusercontent.com/60035342/186486282-d6b38fa4-e54c-439e-920f-f8118be48dbe.mov

**Comment by rajann44** [comment]
@Vandna-Pandey did you check?

**Comment by Vandna-Pandey** [comment]
> 



> @Vandna-Pandey did you check?

Sorry Not yet, Checked.

**Comment by rajann44** [comment]
@Vandna-Pandey No issues. I am able to run it now.
Checkout the code is here: https://github.com/rajann44/SelMvn

**Comment by Vandna-Pandey** [comment]
> @Vandna-Pandey No issues. I am able to run it now. Checkout the code is here: https://github.com/rajann44/SelMvn

Great, Thank you
